eduardoproject/eduardoApp/urls.py
from django.urls import path, include

from . import views

app_name = 'eduardoApp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<slug>/', views.ArticleByCategoryView.as_view(), name='category'),
    path('article/<slug>/', views.DetailView.as_view(), name='detail'), 
    path("vendre/", views.VendreView.as_view(), name="vendre"),
    path('profile',views.ProfileView.as_view(),name='profile'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path("search/", views.search, name="search"),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('validate-order/', views.validate_order, name="validate-order"),
]

eduardoproject/eduardoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from eduardoApp import views as v
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('eduardoApp.urls')),
    path('admin/', admin.site.urls),
    path('register/',v.RegisterView.as_view(),name='register'),
    path('', include("django.contrib.auth.urls")),
    path('logout',v.logout_view,name='logout'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eduardoproject/eduardoApp/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings 
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=False, blank=False)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("eduardoApp:category", kwargs={
            'slug':self.slug
        })

class State(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Article(models.Model):
    article_name = models.CharField(unique=True, max_length=30)
    price = models.FloatField(validators=[MinValueValidator(0)])
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True)
    detail_text = models.TextField(max_length=600, null=True)
    article_image = models.ImageField(upload_to="images/",default="images/noIMG.png", null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    slug = models.SlugField(null=False, blank=False)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.article_name

    def get_absolute_url(self):
        return reverse("eduardoApp:detail", kwargs={
            'slug':self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("eduardoApp:add-to-cart", kwargs={
            'slug':self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("eduardoApp:remove-from-cart", kwargs={
            'slug':self.slug
        })

class OrderArticle(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.article.article_name

    def get_article_total_price(self):
        return self.article.price 

    def get_total_price(self):
        return self.get_article_total_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    articles = models.ManyToManyField(OrderArticle)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField()

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for article in self.articles.all():
            total += article.get_total_price()
        return total

eduardoproject/eduardoApp/forms.py
from django import forms
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Article

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields=["first_name","last_name","username","email","password1","password2"]

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["article_name", "category", "price", "state", "color", "detail_text", "article_image"]
        labels = {
            'article_name': 'Nom de l\'article',
            'category' : 'Catégorie',
            'price': 'Prix',
            'state': 'Etat',
            'color': 'Couleur',
            'detail_text': 'Description',
            'article_image': 'Image',
        }

eduardoproject/eduardoApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.template import loader
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone
from django.contrib import messages
from slugify import slugify
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm, ArticleForm
from .models import Article, Category, Order, OrderArticle, State, Color

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'eduardoApp/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        return Article.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context

class ArticleByCategoryView(generic.ListView):
    template_name = 'eduardoApp/articles_by_category.html'
    context_object_name = 'article_list'

    def get_queryset(self, *args, **kwargs):
        cat = Category.objects.filter(slug=self.kwargs['slug'])[0]
        return Article.objects.filter(category=cat.id, available=True)
     
        
    def get_context_data(self, **kwargs):
        context = super(ArticleByCategoryView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.filter(slug=self.kwargs['slug'])[0]
        return context
        
class DetailView(generic.DetailView):
    model = Article
    template_name = 'eduardoApp/detail.html'

class CartView(LoginRequiredMixin, generic.View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object' : order
            }
            return render(self.request, 'eduardoApp/cart.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "Pas de commande")
            return redirect("eduardoApp:index")

class ProfileView(generic.ListView):
    template_name = 'eduardoApp/profile.html'
    context_object_name = 'order_list'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user.id,ordered=True)

def validate_order(request):
    try:
        order = Order.objects.get(user=request.user, ordered=False)
        for order_article in order.articles.all():
                if not order_article.article.available:
                    messages.warning(request, "Erreur dans la validation du panier. Un ou plusieurs articles indisponible(s).") 
                    return redirect('eduardoApp:cart')
                else:
                    order.ordered = True
                    order.save()
        for order_article in order.articles.all():
            order_article.article.available = False
            order_article.article.save()
            
        messages.info(request, "Commande validée, merci de votre achat !") 
        return redirect("eduardoApp:index")
    except ObjectDoesNotExist:
        messages.error(request, "Impossible de valider les achats")
        return redirect("/")
        
class VendreView(LoginRequiredMixin,generic.View):
    login_url = '/login/'
    def post(self,request):
        form = ArticleForm(request.POST or None, request.FILES)
        if request.method == "POST" and form.is_valid():
            obj=form.save(commit=False)            
            new_slug = form.cleaned_data['article_name']
            obj.slug = slugify(new_slug)
            obj.seller = request.user
            obj.save()
            return redirect("eduardoApp:index")
        return render(request, "eduardoApp/vendre.html", {
            "form":form
        })

    def get(self,request):
        form = ArticleForm()
        return render(request, "eduardoApp/vendre.html", {"form":form})

class RegisterView(generic.View):
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/login")
        else:
            form = RegisterForm()
        return render(request, "register/register.html", {"form":form})

    def get(self, request):
        form = RegisterForm()
        return render(request, "register/register.html", {"form":form})

def logout_view(response):
    logout(response)
    return redirect("eduardoApp:index")

def get_categories(request):
    category_list=Category.objects.all()
    context = {'category_list':category_list}
    return render(request,'eduardoApp/index.html',context)

@login_required
def add_to_cart(request, slug):
    article = get_object_or_404(Article, slug=slug)
    order_article, created = OrderArticle.objects.get_or_create(
        article=article,
        user=request.user,
        ordered=False
        )
    order_set = Order.objects.filter(user=request.user, ordered=False)
    if order_set.exists():
        order=order_set[0]
        if order.articles.filter(article__slug=article.slug).exists():
            messages.warning(request, "Article déjà ajouté au panier")
            return redirect('eduardoApp:detail', slug=slug)

        else:
            messages.info(request, "Article ajouté au panier")
            order.articles.add(order_article)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date = ordered_date)
        order.articles.add(order_article)
        messages.info(request, "Article ajouté au panier")    
    return redirect('eduardoApp:cart')

@login_required
def remove_from_cart(request, slug):
    article = get_object_or_404(Article, slug=slug)
    order_set = Order.objects.filter(user=request.user, ordered=False)
    if order_set.exists():
        order=order_set[0]
        if order.articles.filter(article__slug=article.slug).exists():
            order_article = OrderArticle.objects.filter(
                article=article,
                user=request.user,
                ordered=False
            )[0]
            order.articles.remove(order_article)   
            messages.info(request, "Article supprimé du panier")  
            return redirect("eduardoApp:cart")   
        else:
            messages.info(request, "Article non présent dans le panier")
            return redirect("eduardoApp:detail", slug=slug)

    else:
        messages.info(request, "Panier vide")
        return redirect("eduardoApp:detail", slug=slug)

def is_valid_queryparam(param):
    return param != '' and param is not None

def filter(request):
    qs = Article.objects.all()
    categories = Category.objects.all()
    category = request.GET.get('category')
    priceMin = request.GET.get('priceMin')
    priceMax = request.GET.get('priceMax')
    title_contains_query = request.GET.get('title_contains')

    if is_valid_queryparam(title_contains_query):
        qs = qs.filter(article_name__icontains=title_contains_query)

    if is_valid_queryparam(category) and category!= 'Tous':
        qs = qs.filter(category__name=category)

    if is_valid_queryparam(priceMin):
        qs = qs.filter(price__gte=priceMin)

    if is_valid_queryparam(priceMax):
        qs = qs.filter(price__lt=priceMax)

    qs = qs.filter(available=True)
    return qs

def search(request):
    qs =filter(request)
    paginator = Paginator(qs, 3)
    page = request.GET.get('page')
    qs = paginator.get_page(page)
    title = request.GET.get('title_contains')
    category = request.GET.get('category')
    priceMin = request.GET.get('priceMin')
    priceMax = request.GET.get('priceMax')

    context= {
        'categories': Category.objects.all(),
        'queryset':qs,
        'title':title,
        'category': category,
        'priceMin': priceMin,
        'priceMax': priceMax,
    }
    return render(request, "eduardoApp/search.html",context)

eduardoproject/eduardoApp/templates/partials/header.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel ="stylesheet" type="text/css" href="{% static 'register/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'eduardoApp/style.css' %}">
    
</head>
    
<nav class="navbar navbar-expand-sm bg-light navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="/eduardo">Eduardo</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Vendre</a>
        </li>
        <form style="display: inline-block;" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <div class="empty-div">
            <li class="nav-item" style="display: inline-block;">
                <a class="nav-link" id="left-item" href="#">Mon panier</a>
            </li>
            <li class="nav-item" style="display: inline-block;">
                <a id="left-item" class="nav-link" href="/login">S'identifier</a>
            </li>

        </div>
    </ul>
</nav>
{% block content%}{% endblock %}

eduardoproject/eduardoApp/templates/partials/header_footer.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel ="stylesheet" type="text/css" href="{% static 'register/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'eduardoApp/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'eduardoApp/search.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'eduardoApp/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'eduardoApp/article.css' %}">
</head>
<nav class="navbar navbar-expand-lg navbar-light  bg-light"> 
  <a class="navbar-brand" href="{% url 'eduardoApp:index' %}" data-abc="true">Eduardo</a> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"> <a class="nav-link"  href="{% url 'eduardoApp:vendre' %}" data-abc="true">Vendre</a> </li>
      <form class="form-inline my-2 my-lg-0" action="{% url 'eduardoApp:search' %}"> 
          <input class="form-control nav-search-bar mr-sm-1" type="text" name="title_contains" placeholder="Que recherchez-vous ?"> 
          <button class="btn btn-outline-success nav-search-btn my-2 my-sm-0"  type="submit" ><i class="fa fa-search"></i></button>
      </form>
 
      <li class="nav-item">
          <a class="nav-link" href="{% url 'eduardoApp:search' %}" style="color:green;"> Recherche avancée</a>
      </li>
    </ul>
    <ul class="navbar-nav mr-right">
      {% if user.is_authenticated %}
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'eduardoApp:profile' %}">Mon compte</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'eduardoApp:cart' %}">Mon panier</a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'logout' %}">Se déconnecter</a>
        </li>
      {% else %}
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'login' %}">S'identifier</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}   
    </div>
  {% endfor %}
{% endif %}

{% block content%}{% endblock %}

  <footer class="footer fixed-bottom">
    <div class="container text-center">
      <p>© 2020 Copyright: Eduardo, réalisé à la </p>
      <a href="https://www.he-arc.ch/"> HE-Arc Ingénierie</a>
    </div>
  </footer>
  <script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "topnav") {
        x.className += " responsive";
      } else {
        x.className = "topnav";
      }
    }
    </script>