eduardoproject/eduardoApp/urls.py
from django.urls import path, include

from . import views

app_name = 'eduardoApp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<slug>/', views.ArticleByCategoryView.as_view(), name='category'),
    path('article/<slug>/', views.DetailView.as_view(), name='detail'), 
    path("vendre/", views.VendreView.as_view(), name="vendre"),
    path('profile',views.ProfileView.as_view(),name='profile'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path("search/", views.search, name="search"),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('validate-order/', views.validate_order, name="validate-order"),
]

eduardoproject/eduardoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from eduardoApp import views as v
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('eduardoApp.urls')),
    path('admin/', admin.site.urls),
    path('register/',v.RegisterView.as_view(),name='register'),
    path('', include("django.contrib.auth.urls")),
    path('logout',v.logout_view,name='logout'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eduardoproject/eduardoApp/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings 
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=False, blank=False)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("eduardoApp:category", kwargs={
            'slug':self.slug
        })

class State(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Article(models.Model):
    article_name = models.CharField(unique=True, max_length=30)
    price = models.FloatField(validators=[MinValueValidator(0)])
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True)
    detail_text = models.TextField(max_length=600, null=True)
    article_image = models.ImageField(upload_to="images/",default="images/noIMG.png", null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    slug = models.SlugField(null=False, blank=False)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.article_name

    def get_absolute_url(self):
        return reverse("eduardoApp:detail", kwargs={
            'slug':self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("eduardoApp:add-to-cart", kwargs={
            'slug':self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("eduardoApp:remove-from-cart", kwargs={
            'slug':self.slug
        })

class OrderArticle(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.article.article_name

    def get_article_total_price(self):
        return self.article.price 

    def get_total_price(self):
        return self.get_article_total_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    articles = models.ManyToManyField(OrderArticle)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField()

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for article in self.articles.all():
            total += article.get_total_price()
        return total

eduardoproject/eduardoApp/forms.py
from django import forms
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Article

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields=["first_name","last_name","username","email","password1","password2"]

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["article_name", "category", "price", "state", "color", "detail_text", "article_image"]
        labels = {
            'article_name': 'Nom de l\'article',
            'category' : 'Catégorie',
            'price': 'Prix',
            'state': 'Etat',
            'color': 'Couleur',
            'detail_text': 'Description',
            'article_image': 'Image',
        }

eduardoproject/eduardoApp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.template import loader
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone
from django.contrib import messages
from slugify import slugify
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm, ArticleForm
from .models import Article, Category, Order, OrderArticle, State, Color

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'eduardoApp/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        return Article.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context

class ArticleByCategoryView(generic.ListView):
    template_name = 'eduardoApp/articles_by_category.html'
    context_object_name = 'article_list'

    def get_queryset(self, *args, **kwargs):
        cat = Category.objects.filter(slug=self.kwargs['slug'])[0]
        return Article.objects.filter(category=cat.id, available=True)
     
        
    def get_context_data(self, **kwargs):
        context = super(ArticleByCategoryView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.filter(slug=self.kwargs['slug'])[0]
        return context
        
class DetailView(generic.DetailView):
    model = Article
    template_name = 'eduardoApp/detail.html'

class CartView(LoginRequiredMixin, generic.View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object' : order
            }
            return render(self.request, 'eduardoApp/cart.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "Pas de commande")
            return redirect("eduardoApp:index")

class ProfileView(generic.ListView):
    template_name = 'eduardoApp/profile.html'
    context_object_name = 'order_list'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user.id,ordered=True)

def validate_order(request):
    try:
        order = Order.objects.get(user=request.user, ordered=False)
        for order_article in order.articles.all():
                if not order_article.article.available:
                    messages.warning(request, "Erreur dans la validation du panier. Un ou plusieurs articles indisponible(s).") 
                    return redirect('eduardoApp:cart')
                else:
                    order.ordered = True
                    order.save()
        for order_article in order.articles.all():
            order_article.article.available = False
            order_article.article.save()
            
        messages.info(request, "Commande validée, merci de votre achat !") 
        return redirect("eduardoApp:index")
    except ObjectDoesNotExist:
        messages.error(request, "Impossible de valider les achats")
        return redirect("/")
        
class VendreView(LoginRequiredMixin,generic.View):
    login_url = '/login/'
    def post(self,request):
        form = ArticleForm(request.POST or None, request.FILES)
        if request.method == "POST" and form.is_valid():
            obj=form.save(commit=False)            
            new_slug = form.cleaned_data['article_name']
            obj.slug = slugify(new_slug)
            obj.seller = request.user
            obj.save()
            return redirect("eduardoApp:index")
        return render(request, "eduardoApp/vendre.html", {
            "form":form
        })

    def get(self,request):
        form = ArticleForm()
        return render(request, "eduardoApp/vendre.html", {"form":form})

class RegisterView(generic.View):
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/login")
        else:
            form = RegisterForm()
        return render(request, "register/register.html", {"form":form})

    def get(self, request):
        form = RegisterForm()
        return render(request, "register/register.html", {"form":form})

def logout_view(response):
    logout(response)
    return redirect("eduardoApp:index")

def get_categories(request):
    category_list=Category.objects.all()
    context = {'category_list':category_list}
    return render(request,'eduardoApp/index.html',context)

@login_required
def add_to_cart(request, slug):
    article = get_object_or_404(Article, slug=slug)
    order_article, created = OrderArticle.objects.get_or_create(
        article=article,
        user=request.user,
        ordered=False
        )
    order_set = Order.objects.filter(user=request.user, ordered=False)
    if order_set.exists():
        order=order_set[0]
        if order.articles.filter(article__slug=article.slug).exists():
            messages.warning(request, "Article déjà ajouté au panier")
            return redirect('eduardoApp:detail', slug=slug)

        else:
            messages.info(request, "Article ajouté au panier")
            order.articles.add(order_article)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date = ordered_date)
        order.articles.add(order_article)
        messages.info(request, "Article ajouté au panier")    
    return redirect('eduardoApp:cart')

@login_required
def remove_from_cart(request, slug):
    article = get_object_or_404(Article, slug=slug)
    order_set = Order.objects.filter(user=request.user, ordered=False)
    if order_set.exists():
        order=order_set[0]
        if order.articles.filter(article__slug=article.slug).exists():
            order_article = OrderArticle.objects.filter(
                article=article,
                user=request.user,
                ordered=False
            )[0]
            order.articles.remove(order_article)   
            messages.info(request, "Article supprimé du panier")  
            return redirect("eduardoApp:cart")   
        else:
            messages.info(request, "Article non présent dans le panier")
            return redirect("eduardoApp:detail", slug=slug)

    else:
        messages.info(request, "Panier vide")
        return redirect("eduardoApp:detail", slug=slug)

def is_valid_queryparam(param):
    return param != '' and param is not None

def filter(request):
    qs = Article.objects.all()
    categories = Category.objects.all()
    category = request.GET.get('category')
    priceMin = request.GET.get('priceMin')
    priceMax = request.GET.get('priceMax')
    title_contains_query = request.GET.get('title_contains')

    if is_valid_queryparam(title_contains_query):
        qs = qs.filter(article_name__icontains=title_contains_query)

    if is_valid_queryparam(category) and category!= 'Tous':
        qs = qs.filter(category__name=category)

    if is_valid_queryparam(priceMin):
        qs = qs.filter(price__gte=priceMin)

    if is_valid_queryparam(priceMax):
        qs = qs.filter(price__lt=priceMax)

    qs = qs.filter(available=True)
    return qs

def search(request):
    qs =filter(request)
    paginator = Paginator(qs, 3)
    page = request.GET.get('page')
    qs = paginator.get_page(page)
    title = request.GET.get('title_contains')
    category = request.GET.get('category')
    priceMin = request.GET.get('priceMin')
    priceMax = request.GET.get('priceMax')

    context= {
        'categories': Category.objects.all(),
        'queryset':qs,
        'title':title,
        'category': category,
        'priceMin': priceMin,
        'priceMax': priceMax,
    }
    return render(request, "eduardoApp/search.html",context)

eduardoproject/eduardoApp/templates/eduardoApp/articles_by_category.html
{% extends 'partials/header_footer.html' %}
{% load static %}
<head>  
</head>
{% block content%}
<main role="main" class="container">
    <div class="page">
        <h2>
            {% if article_list.count == 0 %}
                Aucune offre 
            {% elif article_list.count == 1 %}
                1 offre 
            {% else %}
                {{ article_list.count }} offres 
            {% endif %}
            dans <strong>{{ category }}</strong>
           </h2>
        <div class="articles_preview">
            {% for article in article_list %}
                        <div class="articles_preview_one">
                            <div class="articles_preview_image">
                                <span></span>
                                <a href="{{ article.get_absolute_url }}">
                                <img src="{{ article.article_image.url }}"></a>
                            </div>
                            <div class="articles_preview_details">
                                <strong>
                                    <a href="{{ article.get_absolute_url }}">{{ article.article_name }}</a>
                                </strong>
                                <div class="articles_preview_price">
                                    <strong> CHF {{ article.price |floatformat:"2" }}.-</strong>
                                </div>                           
                            </div>
                        </div>
                {% endfor %}
            </div>
    </main>
{% endblock %}

eduardoproject/eduardoApp/templates/eduardoApp/cart.html
{% extends 'partials/header_footer.html' %}

{% load static %}

{% block content%}
<main role="main" class="container">
<div class="cart_page">
  <table class="table product-table mb-0">
    <h2>Votre panier</h2>

    <!-- Table head -->
    <thead class="mdb-color lighten-5">
      <tr>
        <th></th>
        <th class="font-weight-bold">
          <strong>Article</strong>
        </th>
        <th class="font-weight-bold">
          <strong>Couleur</strong>
        </th>
        <th></th>
        <th class="font-weight-bold">
          <strong>Prix</strong>
        </th>
        <th></th>
      </tr>
    </thead>
    <!-- /.Table head -->

    <!-- Table body -->
    <tbody>
      {% for order_article in object.articles.all %}
          <!-- rows -->
          <tr>
          <th>
            <div class="cart_articles_preview_image">
              <span></span>
              <a href="{{ order_article.article.get_absolute_url }}">
              <img src="{{  order_article.article.article_image.url }}"></a>
          </div>
          </th>
          <td class="polol">
            <h5>
              <strong><a href="{{ order_article.article.get_absolute_url }}">{{ order_article.article.article_name }}</a></strong>
            </h5>
          </td>
          <td>{{ order_article.article.color }}</td>
          <td></td>
          <td>{{ order_article.article.price |floatformat:"2" }} CHF</td>
          <td>
            <a href="{% url 'eduardoApp:remove-from-cart' order_article.article.slug %}" id="button" class="btn btn-sm btn-danger">X</a>
          </td>
        </tr>
        <!-- /. rows -->
      {% endfor %}

      <!-- buttons -->
      <tr>
        <td  class="font-weight-bold" colspan="4">Total</td>
        <td class="font-weight-bold" >{{ object.get_total |floatformat:"2"  }} CHF</td>
        <td></td>
      </tr>
      <!-- /. buttons -->
    </tbody>
    <!-- /.Table body -->
  </table>
  <hr>
  <a href="{% url 'eduardoApp:index' %}" id=button class="btn btn-primary">Continuer les achats</a>
  <a href="{% url 'eduardoApp:validate-order' %}" id=button class="btn btn-warning">Valider les achats</a>
</div>
{% endblock %}

eduardoproject/eduardoApp/templates/eduardoApp/detail.html
{% extends 'partials/header_footer.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'static/eduardoApp/style.css' %}">

{% block content%}

<div class="article_page">
    <div class="article">
        <div class="article_image">
            <span></span>
            <img src="{{ article.article_image.url }}">
        </div>
        <div class="article_details">
            <h1>{{ article.article_name }}</h1>
            <p>Publié par {{ article.seller }}</p> 
            <h2 class="price"> CHF {{ article.price |floatformat:"2" }}.-</h2>
            {% if user.is_authenticated %}

            {% ifequal article.seller user%}
                <p class="not_buyable">Vous ne pouvez pas acheter une offre que vous avez publiée</p>
            {% else %}
            {% if article.available %}
                <a href="{{ article.get_add_to_cart_url }}" id="button" class="btn btn-primary">Ajouter au panier</a>
            {% else %}
                <p class="not_buyable">Desolé, cet article a déja été vendu !</p>
            {% endif %}
            {% endifequal %}
            {% endif %}


            <h2> Détails </h2>
            <ul>
                <li>Etat : {{ article.state }}</li>
                <li>Couleur : {{ article.color }}</li>
                <li>Catégorie : {{ article.category }}</li>
            </ul>
            <h2>Description</h2>
            <p class="description">{{article.detail_text}}</p>
        </div>
    </div>
</div>
{% endblock %}

eduardoproject/eduardoApp/templates/eduardoApp/index.html
{% extends 'partials/header_footer.html' %}
{% load static %}
<head>
</head>
{% block content %}
<main role="main" class="container">
<div class="page">
    <h2>Toutes les catégories</h2>
            <div class="index_categorys">
                {% for category in category_list %}
                    <div class=" card index_category">
                        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                    </div>
                {% endfor %}
            </div>
            <hr/>

            <h2>Dernières offres</h2>
            <div class="articles_preview">
                {% for article in article_list %}
                    {% if article.available %}
                        <div class="articles_preview_one">
                            <div class="articles_preview_image">
                                <span></span>
                                <a href="{{ article.get_absolute_url }}">
                                <img src="{{ article.article_image.url }}"></a>
                            </div>
                            <div class="articles_preview_details">
                                <strong>
                                    <a href="{{ article.get_absolute_url }}">{{ article.article_name }}</a>
                                </strong>
                                <div class="articles_preview_price">
                                    <strong> CHF {{ article.price |floatformat:"2" }}.-</strong>
                                </div>                           
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a class="pagination-item" href="?page=1">&laquo; first</a>
                        <a class="pagination-item" href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    
                    <span class="current pagination-number">
                        {{ page_obj.number }}
                    </span>
            
                    {% if page_obj.has_next %}
                        <a class="pagination-item" href="?page={{ page_obj.next_page_number }}">next</a>
                        <a class="pagination-item" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
</main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      
{% endblock %}

eduardoproject/eduardoApp/templates/eduardoApp/profile.html
{% extends 'partials/header_footer.html' %}

{% load static %}

{% block content%}
<main role="main" class="container">
  <div class="cart_page">
    <table class="table product-table mb-0">
      <h2 class="h2_profile">Bienvenue {{user.first_name}} {{user.last_name}} !
      {% if order_list %} 
        <h3>Historique des achats</h3>
        <!-- Table head -->
        <thead class="mdb-color lighten-5">
            <tr>
              <th></th>
              <th class="font-weight-bold">
                <strong>Article</strong>
              </th>
              <th class="font-weight-bold">
                <strong>Date de l'achat</strong>
              </th>
              <th></th>
              <th class="font-weight-bold">
                <strong>Prix</strong>
              </th>
              <th></th>
            </tr>
          </thead>
          <!-- /.Table head -->

          <!-- Table body -->
          <tbody>
            {% for order in order_list %}
              <!-- rows -->
              {% for article in order.articles.all %}
                <tr>
                  <th>
                    <div class="cart_articles_preview_image">
                      <span></span>
                      <a href="{{ article.article.get_absolute_url }}">
                      <img src="{{  article.article.article_image.url }}"></a>
                    </div>
                  </th>
                  <td class="polol">
                    <h5>
                      <strong><a href="{{ article.article.get_absolute_url }}">{{ article.article.article_name }}</a></strong>
                    </h5>
                  </td>
                  <td>{{ order.ordered_date }}</td>
                  <td></td>
                  <td>{{ article.article.price |floatformat:"2" }} CHF</td>
                  <td></td>
                </tr>
                  <!-- /. rows -->
              {% endfor %}
            {% endfor %}
          </tbody>
        <!-- /.Table body -->
      </table>
        <hr>
        <div>
            <p>Merci de votre confiance.</p>
        </div>
    {% else %}
      <h3>Aucun achat effectué !</h3>
    {% endif %}
  </div>
</main>
{% endblock %}

eduardoproject/eduardoApp/templates/eduardoApp/search.html
{% extends 'partials/header_footer.html' %}
{% load static %}
<head>
   
</head>
{% block content %}
<main role="main" class="container">
<div class="search_form">
    <h2>Recherche avancée</h2>
    <form method="GET" action=".">
        <div class="form-row">
            <div class="form-group col-md-3 col-lg-4">
                <label for="priceMin">Nom de l'article</label>  
                <input class="form-control py-2 border-right-0 border"  type="search" name="title_contains" placeholder="Que recherchez-vous ?" value="{% if title %}{{title}}{% endif %}"/>
            </div> 
            <div class="form-group col-md-2">
                <label for="category">Catégorie</label>
                <select id="category" class="form-control" name="category">
                    <option selected>{% if category %}{{category}}{% else %}Tous{% endif %}</option>
                    {% for cat in categories %}
                    <option value="{{ cat }}">{{ cat }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-2 col-lg-2">
                <label for="priceMin">Prix min</label>
                <input type="number" min=1 class="form-control" id="priceMin" name="priceMin" value="{% if priceMin %}{{priceMin}}{% else %}1{% endif %}">
            </div>
            <div class="form-group col-md-2 col-lg-2">
                <label for="priceMax">Prix max</label>
                <input type="number" min=2 class="form-control" id="priceMax"  name="priceMax" value="{% if priceMax %}{{priceMax}}{% else %}100000{% endif %}">
            </div>
            <div class="form-group col-md-2 col-lg-2">
                <label for="search" style="visibility:hidden;">Hidden</label>
                <button class="btn btn-outline-success" type="submit">Chercher</button>     
            </div> 
        </div>
    </form>
    <hr/>
    <p class="search_results_label"> 
       {% if queryset.paginator.count == 0 %}
            Aucune offre 
        {% elif queryset.paginator.count  == 1 %}
             1 offre 
        {% else %}
             {{queryset.paginator.count}} offres 
        {% endif %}
    </p>
    <div class="articles_preview">
        {% for article in queryset %}
            <div class="articles_preview_one">
                <div class="articles_preview_image">
                    <span></span>
                    <a href="{{ article.get_absolute_url }}">
                        <img src="{{ article.article_image.url }}">
                    </a>
                </div>
                <div class="articles_preview_details">
                    <strong>
                        <a href="{{ article.get_absolute_url }}">{{ article.article_name }}</a>
                    </strong>
                    <div class="articles_preview_price">
                        <strong> CHF {{ article.price |floatformat:"2" }}.-</strong>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="pagination">
        {% if queryset.has_previous %}
           <a class="pagination-item" href="?page={{ queryset.previous_page_number }}{% if request.GET.title_contains %}&title_contains={{ request.GET.title_contains }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}{% if request.GET.priceMin %}&priceMin={{ request.GET.priceMin }}{% endif %}{% if request.GET.priceMax %}&priceMax={{ request.GET.priceMax }}{% endif %}">Précédent</a>
        {% endif %}
        {% for num in queryset.paginator.page_range %}
            {% if queryset.number == num %}
                <span class="pagination-number pagination-current">{{ num }}</span>
            {% elif num > queryset.number|add:'-3' and num < queryset.number|add:'3' %}
                <a class="pagination-number" href="?page={{ num }}{% if request.GET.title_contains %}&title_contains={{ request.GET.title_contains }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}{% if request.GET.priceMin %}&priceMin={{ request.GET.priceMin }}{% endif %}{% if request.GET.priceMax %}&priceMax={{ request.GET.priceMax }}{% endif %}"> {{ num }} </a>
            {% endif %}
        {% endfor %}
        {% if queryset.has_next %}
            <a class="pagination-item" href="?page={{ queryset.next_page_number }}{% if request.GET.title_contains %}&title_contains={{ request.GET.title_contains }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}{% if request.GET.priceMin %}&priceMin={{ request.GET.priceMin }}{% endif %}{% if request.GET.priceMax %}&priceMax={{ request.GET.priceMax }}{% endif %}">Suivant</a>
        {% endif %}
    </div>
</main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      
{% endblock %}

eduardoproject/eduardoApp/templates/eduardoApp/vendre.html
{% extends 'partials/header_footer.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="form_article">
    <h2>Publier un article pour la vente</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form|crispy }}
        <button type="submit" class="btn-btn-primary">Publier</button>
    </form>
</div>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}
{% endblock %}